#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: 계정·키·배포 대상 준비 (Wayfinder 티켓 #6)
#
# 실행: bash scripts/setup-keys.sh          (설재원 PC, 발급 + .env + GitHub)
#       ENV_FILE=.env bash scripts/setup-keys.sh   (차시헌 PC에서 대면 입력 시:
#       콘솔 발급 단계는 Enter로 넘기고 값만 붙여 넣는다)
#
# 키 값은 .env 와 GitHub Actions 에만 간다. 이슈·카톡에는 적지 않는다(SECURITY.md).
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "공무원 맛집 지도: 계정·키·배포 대상 준비"

# ── 1. Cloudflare Pages 프로젝트 ─────────────────────────────────────────
stage "Cloudflare Pages: 프로젝트 생성"
say "배포 대상을 먼저 만든다. 이 도메인이 다음 단계의 네이버 지도 allowlist에 들어간다."
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages/create/pages"
step "Workers & Pages → Create → Pages 탭 → 'Upload assets'(직접 업로드) 선택."
step "Project name 에 officialdeliciousmap 을 넣고 프로젝트를 만든다. (CI가 wrangler로 올릴 것이라 지금 파일 업로드는 필요 없다. 빈 업로드가 막히면 index.html 하나짜리 zip을 올려도 된다.)"
step "생성 후 표시되는 도메인(예: officialdeliciousmap.pages.dev)을 확인한다."
ask CLOUDFLARE_PAGES_PROJECT "Pages 프로젝트 이름:"
ask PAGES_URL "배포 도메인(https://... 형태로):"
write_env CLOUDFLARE_PAGES_PROJECT "$CLOUDFLARE_PAGES_PROJECT"
write_env PAGES_URL "$PAGES_URL"
set_var CLOUDFLARE_PAGES_PROJECT "$CLOUDFLARE_PAGES_PROJECT"
pause

# ── 2. Cloudflare 계정 ID + API 토큰 ─────────────────────────────────────
stage "Cloudflare: Account ID 와 API 토큰"
say "CI(#15)가 wrangler 로 배포할 때 쓰는 두 값. GitHub Actions Secrets 로 간다."
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "Workers & Pages 개요 화면 오른쪽 사이드바의 'Account ID' 를 복사한다."
ask_secret CLOUDFLARE_ACCOUNT_ID "Account ID 붙여넣기:"
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "Create Token → 'Edit Cloudflare Workers' 템플릿 → Use template."
step "Permissions 에 'Account · Cloudflare Pages · Edit' 가 있는지 확인(없으면 Add more 로 추가), Account Resources 는 이 계정으로 한정."
step "Continue to summary → Create Token → 토큰을 복사한다(한 번만 보인다)."
ask_secret CLOUDFLARE_API_TOKEN "API 토큰 붙여넣기:"
warn "토큰은 .env 에 쓰지 않는다. GitHub Secrets 에만 둔다."
set_secret CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
set_secret CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"
pause

# ── 3. 네이버 지도 클라이언트 키(새 발급) ───────────────────────────────
stage "네이버 클라우드: Maps 클라이언트 키 새로 발급"
say "목업 키와 분리한 새 Application. 공개돼도 되는 키지만 Web 서비스 URL allowlist 로만 보호된다."
open_url "https://console.ncloud.com/naver-service/application"
step "Application 등록 → 이름: officialdeliciousmap → Service 선택에서 Maps 의 Dynamic Map(Web) 체크."
step "Web 서비스 URL 에 두 줄 등록: ${PAGES_URL:-https://officialdeliciousmap.pages.dev}  와  http://localhost:8000"
step "저장 후 목록에서 '인증 정보' → Client ID 를 복사한다. (신규 Application 은 스크립트 파라미터가 ncpKeyId 일 수 있다. 콘솔 안내문에 적힌 파라미터 이름을 같이 확인한다.)"
ask NAVER_MAP_CLIENT_ID "Maps Client ID:"
ask NAVER_MAP_KEY_PARAM "스크립트 파라미터 이름(ncpKeyId 또는 ncpClientId):"
write_env NAVER_MAP_CLIENT_ID "$NAVER_MAP_CLIENT_ID"
write_env NAVER_MAP_KEY_PARAM "$NAVER_MAP_KEY_PARAM"
set_var NAVER_MAP_CLIENT_ID "$NAVER_MAP_CLIENT_ID"
set_var NAVER_MAP_KEY_PARAM "$NAVER_MAP_KEY_PARAM"
pause

# ── 4. 네이버 검색 API(지오코딩) → NAVER API HUB ─────────────────────
stage "네이버 클라우드: NAVER API HUB 검색 API 키"
say "개발자센터 검색 API는 2026-06 NAVER API HUB(네이버 클라우드)로 이관됐다. 새 발급은 HUB에서만 된다."
say "#8 결정대로 설재원이 하나 발급해 두 PC의 .env 에 넣는다. CI 는 쓰지 않는다."
open_url "https://console.ncloud.com/naver-api-hub/application"
step "메뉴 → 전체 서비스 → Application Services → NAVER API HUB → [서비스 이용 신청](약관 동의)."
step "Application 등록 → 이름: officialdeliciousmap (영문·숫자·하이픈, 20자) → API 선택에서 '검색' 의 지역(local) 체크. Web 서비스 URL 은 필요 없다."
step "등록 후 '인증 정보' 에서 Client ID(X-NCP-APIGW-API-KEY-ID) 와 Client Secret(X-NCP-APIGW-API-KEY) 을 복사한다."
note "엔드포인트: https://naverapihub.apigw.ntruss.com/search/v1/local (헤더 X-NCP-APIGW-API-KEY-ID / X-NCP-APIGW-API-KEY). 한시 무료, 검색 합산 월 775,000회·일 25,000회·키당 50 RPS."
ask NAVER_SEARCH_CLIENT_ID "HUB Client ID:"
ask_secret NAVER_SEARCH_CLIENT_SECRET "HUB Client Secret:"
write_env NAVER_SEARCH_CLIENT_ID "$NAVER_SEARCH_CLIENT_ID"
write_env NAVER_SEARCH_CLIENT_SECRET "$NAVER_SEARCH_CLIENT_SECRET"
pause

# ── 5. Gemini API 키 + 결제 ──────────────────────────────────────────────
stage "Google AI Studio: Gemini API 키(유료 Tier 1)"
say "#4 조사 결과 무료 티어(20 RPD)로는 프로토타입도 안 된다. 결제가 연결된 프로젝트에서 키를 만든다."
open_url "https://aistudio.google.com/apikey"
step "'API 키 만들기' → 새 Google Cloud 프로젝트 생성(이름: officialdeliciousmap) 또는 기존 선택."
step "같은 화면의 '결제 설정'(Set up billing) 으로 그 프로젝트에 결제 계정을 연결한다. 연결되면 플랜이 'Tier 1' 로 바뀐다."
step "키를 복사한다(AIza... 로 시작). 주의: gemini-2.5-flash 는 신규 계정에 닫혔다. 기본 모델은 gemini-3.6-flash."
ask_secret GEMINI_API_KEY "Gemini API 키:"
write_env GEMINI_API_KEY "$GEMINI_API_KEY"
write_env GEMINI_MODEL "gemini-3.6-flash"
open_url "https://console.cloud.google.com/billing/budgets"
step "예산 만들기 → 프로젝트 officialdeliciousmap → 금액 20 USD → 50/90/100% 이메일 알림."
warn "예산은 알림만 준다. Gemini API 에는 지출 상한(hard cap) 이 없다. 최악 전량 폴백 \$41(#4) 이라 20 USD 알림이면 충분히 이르다."
pause

# ── 6. GitHub 협업자 확인 ────────────────────────────────────────────────
stage "GitHub: 협업자·Secrets 확인"
say "차시헌 님(sihun0927-sketch) 은 이미 collaborator 다. 여기서는 등록된 값만 확인한다."
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  say "collaborators:"; gh api repos/snowjaewon/OfficialDeliciousMap/collaborators --jq '.[].login' | sed 's/^/    /'
  say "secrets:";       gh secret list   | sed 's/^/    /'
  say "variables:";     gh variable list | sed 's/^/    /'
else
  warn "gh 가 준비되지 않아 확인을 건너뛴다. 브라우저에서 확인:"
  open_url "https://github.com/snowjaewon/OfficialDeliciousMap/settings/secrets/actions"
fi
pause

finish
say "다음: 티켓 #6 에 '키가 어디 있는지'(값 아님)·Pages URL·allowlist 도메인만 적고 닫는다."
